version: "3"

services:
  tradebot:
    build: .
    restart: unless-stopped
    volumes:
#      - ./user.cfg:/app/user.cfg
#      - ./data:/app/data
#      - ./logs:/app/logs
      - ./:/app
    command: python -m binance_trade_bot

  api:
    build: .
    restart: unless-stopped
    volumes:
      #- ./data:/app/data
      #- ./logs:/app/logs
      #- ./user.cfg:/app/user.cfg
      - ./:/app
    ports:
      - 5123:5123
    command: gunicorn binance_trade_bot.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123
    depends_on:
      - tradebot

  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./data/config:/config
      - ./data:/data
    ports:
      - 3000:3000
